version: "3.5"

services:
  postgres-distage:
    container_name: postgres-distage
    image: postgres
    environment:
      POSTGRES_USER: distage
      POSTGRES_PASSWORD: 'distage'
      POSTGRES_DB: distage
    expose:
    - 5432
    ports:
    - 5432:5432
    volumes:
    - ./db/postgresql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
    - persistence-distage

networks:
  persistence-distage:
    name: persistence-distage
    driver: bridge
