name: Build

on:
  workflow_dispatch:
    inputs: {}
  push:
    branches: [ "develop" ]
    tags: [ "v**" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  sbt-test:
    runs-on: ubuntu-latest
    steps:
    - uses: sbt/setup-sbt@v1 # setup sbt
    - uses: actions/checkout@v2
    - name: Run tests
      run: sbt +test
  build-native:
    runs-on: ubuntu-latest
    steps:
      - uses: sbt/setup-sbt@v1 # setup sbt
      - uses: actions/checkout@v2
      - name: Build native app
        run: sbt "project bifunctor-tagless; GraalVMNativeImage/packageBin"
      - name: Check native app
        run: ./bifunctor-tagless/target/graalvm-native-image/bifunctor-tagless :help
